### ISSUE TITLE
Import fail

### ISSUE THREAD

**Issue by interequipment** [navinbhudiya/magento2-import-export-category#2]
What should be the correct format for CSV??

**Comment by Akki-8388** [comment]
I have facing same issue is there any solution for import time @interequipment @navinbhudiya

**Comment by navinbhudiya** [comment]
CSV must be in **utf-8** format otherwise it not worked.
if you creating CSV using Microsoft Office then it not worked. used libra office software to create CSV.

**Comment by Akki-8388** [comment]
okay thank you bro,I will try and let you know @navinbhudiya .

**Comment by navinbhudiya** [comment]
> okay thank you bro,I will try and let you know @navinbhudiya .

you can also contact me on my skype :navinbhudiya2

**Comment by interequipment** [comment]
@Akki-8388 this extension solved my problem. https://github.com/macopedia/CategoryImporter
